config/routes.rb
Rails.application.routes.draw do
  
  
  resources :tags, except: [:index] do
    authenticated :user do
      post 'approve'
      post 'reject'
    end
  end
  
  get '/home/', to: 'poems#home'

  get '/admin/', to: 'admin#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
    
  authenticated :user do
    get '/poems/', to:'poems#index', as: :view_poems
    
    get '/tags', to: 'tags#index', as: :view_tags
  
    get 'poems/submitted/', to: 'poems#submitted'

    resources :poems, except: [:index] do
      member do
        post 'approve'
        post 'reject'
        get 'teacher_profile'
      end
    end

  end
  
  unauthenticated :user do
   get '/poems/', to: 'poems#home'
  end

  if Rails.env.production?
     get '404', :to => 'application#page_not_found'
  end

  root to: 'poems#home'

  

  

end

app/models/poem.rb
class Poem < ActiveRecord::Base
    has_many :tags
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
    mount_uploader :release, ReleaseUploader
    validates :attachment, :teacher_name, :county, :email, :student_name, :school, :grade, :student_teacher_name, :title, :tag_list, :release, presence: true # Make sure the owner's name is present.
    #acts_as_taggable
    acts_as_taggable_on :tags

    # trying to override tag saving    
    # def find_or_create_tags_from_list_with_context(tag_list, context)
    #     for tag in tag_list:
    #         new_tag = Tag.new(:name => tag, :status => "Pending")
    #         new_tag.s
    #     end
    # end
    
    
    def pending?
        return true if self.status == 'Pending'
        return false
    end
    
    def rejected?
        return true if self.status == 'Rejected'
        return false
    end
    
    def approved?
        return true if self.status == 'Approved'
        return false
    end
    
    def teacher_profile_link
        require 'mechanize'
        require 'nokogiri'
        
        agent = Mechanize.new
        if page = agent.get('https://c3cmr117.caspio.com/dp.asp?AppKey=81ec40002ba02c780e474240af87') 
        
            form = page.form_with(:id => 'caspioform')
        
            names = self.teacher_name.split(" ")
            first_name = names[0]
            last_name = names.last
            form["Value1_1"] = last_name
            form["Value2_1"] = first_name
            page = agent.submit(form)
        
            if link = page.link_with(:text => "View Details")
                page2 = link.click
                return page2
            end
        end
    end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
    skip_before_filter :authenticate_user!
    
    def poem_params
        params.require(:poem).permit(:teacher_name, :county, :email, :student_name, :school, :grade, :student_teacher_name, :title, :tag_list, :attachment, :poem, :release)
    end
    
    def index
        @poems = Poem.all.order('created_at DESC')
    end
    
    def show
        id = params[:id]
        @poem = Poem.find(id)
        @url_test = request.base_url
        @url_test = "http://" + @url_test[8, @url_test.length]
        
        @tag_objects = []
        if @poem.tag_list
            @tags = @poem.tag_list

            @tags.each do |tag|
                query = Tag.where(name: tag).first
                if query.blank?
                    new_tag = Tag.new(:name => tag, :status => "Pending")
                    if not new_tag.save
                        flash[:warning] = "Please fix formatting."
                        render view_tags_path
                    end
                    @tag_objects.push(new_tag)
                else
                    @tag_objects.push(query)
                end
            end
        end
    end
    
    def new
        
    end
    
    def approve 
        poem = Poem.find(params[:id])
        poem.update_attributes(:status => "Approved")
        flash[:notice] = "You successfully approved this poem."
        redirect_to view_poems_path
    end
    
    def reject
        poem = Poem.find(params[:id])
        poem.update_attributes(:status => "Rejected")
        flash[:notice] = "You successfully rejected this poem."
        redirect_to view_poems_path
    end
    
    def create
        @poem = Poem.new(poem_params)
        if @poem.save
            #create tags
            for tag in @poem.tag_list
                new_tag = Tag.new(:name => tag, :status => "Pending")
                puts new_tag
                if not new_tag.save
                    flash[:warning] += tag + " was not formatted correctly"
                end
            end
            Notifier.notify(@poem.teacher_name).deliver_later
            redirect_to poems_submitted_path
        else
            flash.now[:warning] = "Please fill in Missing Fields."
            render new_poem_path
        end   
    end
    
    def home
        @poems = Poem.where("status = 'Approved'").order(:created_at).reverse_order.paginate(page: params[:page], per_page: 9)
    end
    
    def teacher_profile
        require 'mechanize'
        require 'nokogiri'
        
        @poem = Poem.find(params[:id])
        @page = @poem.teacher_profile_link

        if @page.nil?
            flash[:notice] = "Teacher does not exist"
            redirect_to view_poems_path
        end
    end
    
end  

app/views/poems/home.html.haml
!!! 5
%html
  
  %head
    %title California Poets Submitted Poems
    = stylesheet_link_tag "home"
    = stylesheet_link_tag "admindash"
    = javascript_include_tag 'home'
    = csrf_meta_tags
  // , margin: "10" align: "left"
      

  %body
    .logo
      = link_to image_tag("https://static.wixstatic.com/media/a0cfee_3825840911504adfac05ff6e22bf7b6c.jpg/v1/fill/w_198,h_134,al_c,q_80,usm_0.66_1.00_0.01/a0cfee_3825840911504adfac05ff6e22bf7b6c.webp", 
      width: "280px", height: "189px", align: "left", border: "10px"),
      'http://www.californiapoets.org/', :id => "CPITS_image", :target => "_blank"

    .donate_img
      = link_to image_tag("donate.png", align: "right"), "http://www.californiapoets.org/for-donors", :id => "Donate_image", :target => "_blank"
    
    %h1.title Fresh poems from our students across California
    #main

  %poems_container{:id => "poems_container"}
    - @poems.each do |poem|
      .poems_box{:id => "poem#{poem.id}"}
        %h1.poems_title{:id => "poem_title#{poem.id}"}= poem.title
        %p.poems_text{:id => "poem_text_#{poem.id}"}= poem.poem
        %span.author_name=poem.student_name
        
  %span.ending_line
    %span
      Help us continue our program
    %span
      One line can change a life
  = will_paginate @poems, inner_window: 2, outer_window: 2
  .redirect_link 
    = link_to 'Back to California Poets', 'http://www.californiapoets.org/'

app/views/poems/index.html.haml
= stylesheet_link_tag "admindash"
= javascript_include_tag 'admindash'


// .rightbutton= link_to 'Log Out', destroy_user_session_path, :method=>'delete', :class=>"btn white logout"
// .rightbutton= link_to 'Gallery', { action: "home" }, :method=>'get', :class=> "btn white gallery"
.heading-button-container
	%h1 List of All Submitted Poems in Database
	.switch-button
		%div#options
			%div 
				=link_to "Poems", poems_path, :class=>"btn white poem-tag"
			%div
				=link_to "Tags", view_tags_path, :class=>"btn white poem-tag"
			
.container
	.tabs-container
		%ul.tabs
			%li
				=link_to "Pending Approval", "javascript:openTab(event, 'tab-1')", :id => "current", :class => "tab-link"
			%li 
				=link_to "All Poems", "javascript:openTab(event, 'tab-2')", :class => "tab-link"
			%li 
				=link_to "Approved Poems", "javascript:openTab(event, 'tab-3')", :class => "tab-link"
			%li 
				=link_to "Rejected Poems", "javascript:openTab(event, 'tab-4')", :class => "tab-link"
		
		#tab-1.tab-content
			%table#poems
				%thead
					%tr
						%th Poet Teacher
						%th County
						%th Email
						%th Student Name
						%th School
						%th Grade
						%th Teacher
						%th Title of Poem
						%th Tags
						%th Status
						%th Poem/Images
						%th Release
						%th Submission Date
						%th Approve
						%th Reject
				%tbody
					- @poems.each do |poem| 
						- if poem.status == "Pending"
							%tr
								%td= link_to poem.teacher_name, teacher_profile_poem_path(poem.id)
								%td= poem.county
								%td= poem.email
								%td= poem.student_name
								%td= poem.school
								%td= poem.grade
								%td= poem.student_teacher_name
								%td= link_to poem.title, poem_path(poem)
								%td= poem.tag_list
								%td= poem.status
								%td= link_to "Download", poem.attachment_url
								%td= link_to "Download", poem.release_url  
								%td= poem.created_at.to_date.strftime("%B %d, %Y")
								%td= button_to( "Approve", approve_poem_path(poem.id), :class => "btn small-btn")
								%td= button_to( "Reject", reject_poem_path(poem.id), :class => "btn small-btn")
								
		#tab-2.tab-content
			%table#poems
				%thead
					%tr
						%th Poet Teacher
						%th County
						%th Email
						%th Student Name
						%th School
						%th Grade
						%th Teacher
						%th Title of Poem
						%th Tags
						%th Status
						%th Poem/Images
						%th Release
						%th Submission Date
				%tbody
					- @poems.each do |poem|
						%tr
							%td= poem.teacher_name 
							%td= poem.county
							%td= poem.email
							%td= poem.student_name
							%td= poem.school
							%td= poem.grade
							%td= poem.student_teacher_name
							%td= link_to poem.title, poem_path(poem)
							%td= poem.tag_list
							%td= poem.status
							%td= link_to "Download", poem.attachment_url
							%td= link_to "Download", poem.release_url
							%td= poem.created_at.to_date.strftime("%B %d, %Y")
		#tab-3.tab-content
			%table#poems
				%thead
					%tr
						%th Poet Teacher
						%th County
						%th Email
						%th Student Name
						%th School
						%th Grade
						%th Teacher
						%th Title of Poem
						%th Tags
						%th Status
						%th Poem/Images
						%th Release
						%th Submission Date
				%tbody
					- @poems.each do |poem| 
						- if poem.status == "Approved"
							%tr
								%td= poem.teacher_name 
								%td= poem.county
								%td= poem.email
								%td= poem.student_name
								%td= poem.school
								%td= poem.grade
								%td= poem.student_teacher_name
								%td= link_to poem.title, poem_path(poem)
								%td= poem.tag_list
								%td= poem.status
								%td= link_to "Download", poem.attachment_url
								%td= link_to "Download", poem.release_url
								%td= poem.created_at.to_date.strftime("%B %d, %Y")
								%td= button_to( "Reject", reject_poem_path(poem.id), :class => "btn small-btn")
		#tab-4.tab-content
			%table#poems
				%thead
					%tr
						%th Poet Teacher
						%th County
						%th Email
						%th Student Name
						%th School
						%th Grade
						%th Teacher
						%th Title of Poem
						%th Tags
						%th Status
						%th Poem/Images
						%th Release
						%th Submission Date
				%tbody
					- @poems.each do |poem| 
						- if poem.status == "Rejected"
							%tr
								%td= poem.teacher_name 
								%td= poem.county
								%td= poem.email
								%td= poem.student_name
								%td= poem.school
								%td= poem.grade
								%td= poem.student_teacher_name
								%td= link_to poem.title, poem_path(poem)
								%td= poem.tag_list
								%td= poem.status
								%td= link_to "Download", poem.attachment_url
								%td= link_to "Download", poem.release_url
								%td= poem.created_at.to_date.strftime("%B %d, %Y")
								%td= button_to( "Approve", approve_poem_path(poem.id), :class => "btn small-btn")
					
%script
	document.getElementById("current").click();

app/views/poems/new.html.haml
= stylesheet_link_tag "submitpoemform"


.container
  .info
   
    %span
  = form_tag poems_path, :class => "newpoem_form", :multipart => true do
    %header.header
      = link_to image_tag("https://static.wixstatic.com/media/a0cfee_3825840911504adfac05ff6e22bf7b6c.jpg/v1/fill/w_198,h_134,al_c,q_80,usm_0.66_1.00_0.01/a0cfee_3825840911504adfac05ff6e22bf7b6c.webp",
      ), '/', :id => "CPITS_image"   
      %h2 Submit a poem
    .content
      .form
        %h4 Poet-Teacher Information
        .form-row
          .input-group
            = label :poem, :teacher_name, 'Poet Teacher Name'
            = text_field :poem, :teacher_name, :class=> "form-control", :id=> "poem_teacher_name", :placeholder => 'ex: John Smith', :err => 'Poet Teacher Name'
        .form-row
          .input-group
            = label :poem, :email, 'Email'
            = text_field :poem, :email, :class=> "form-control", :id=> "poem_email", :placeholder => 'ex: jSmith@gmail.com', :err => "Email"           
        %h4 Student Information
        
        %entry1.student_instance
        
          .form-row
            .input-group
              = label :poem, :student_name, 'Student Name', :class => "label_student_name control-label"
              = text_field :poem, :student_name, :class => "entry_box input_student form-control", :id=> "poem_student_name", :placeholder => 'ex: Ivette Flores', :err => "Student Name"
            .input-group
              = label :poem, :grade, "Grade"
              = select :poem, 'grade', [ 'K', '1', '2', '3', '4', '5' , '6', '7', '8', '9', '10', '11', '12', 'Other']
          .form-row
            .input-group
              = label :poem, :student_teacher_name, 'Teacher Name'
              = text_field :poem, 'student_teacher_name', :class => "entry_box", :id => "poem_student_teacher_name", :type => 'text', :placeholder => 'ex: Nancy Freeman', :err => "Teacher Name"
          
          .form-row
            .input-group
              = label :poem, :school, 'School'
              = text_field :poem, 'school', :class => "entry_box", :id => "poem_school", :type => 'text', :placeholder => 'ex: Berkeley Middle School', :err => "School"
            .input-group
              = label :poem, :county, "County"
              = select :poem, 'county', [ 'Alameda', 'Alpine', 'Amador', 'Butte', 'Calaveras', 'Colusa' , 'Contra Costa', 'Del Norte', 'El Dorado', 'Fresno', 'Glenn', 'Humboldt', 'Imperial', 'Inyo', 'Kern', 'Kings', 'Lake', 'Lassen', 'Los Angeles', 'Madera', 'Marin', 'Mariposa', 'Mendocino', 'Merced', 'Modoc', 'Mono', 'Monterey', 'Napa', 'Nevada', 'Placer', 'Plumas', 'Riverside', 'Sacramento', 'San Benito', "San Bernardino", 'San Diego', 'San Francisco', 'San Joaquin', 'San Luis Obispo', 'San Mateo', 'Santa Barbara', 'Santa Clara', 'Santa Cruz', 'Shasta', 'Sierra', 'Siskiyou', 'Solano', 'Sonoma', 'Stanislaus', 'Sutter', 'Tehama', 'Trinity', 'Tulare', 'Tuolumne', 'Ventura', 'Yolo', 'Yuba', 'Other']

          .form-row
            .input-group
              = label :poem, :title, 'Poem Title'
              = text_field :poem, 'title', :class => "entry_box", :id=> "poem_title", :type => 'text', :placeholder => 'ex: The Road Not Taken', :err => 'Poem Title'
          / Dropdown Trigger
          %a.dropdown-button.btn{"data-activates" => "dropdown1"} Poem tags
          / Dropdown Structure
          %ul#dropdown1.dropdown-content
            %li
              %a{:href => "#!"} Spring
            %li
              %a{:href => "#!"} Summer
            %li.divider
            %li
              %a{:href => "#!"} Fall
            %li
              %a{:href => "#!"} Winter
            %li
              %a{:href => "#!"} Rain
            %li
              %a{:href => "#!"} Halloween
            %li
              %a{:href => "#!"} Snow
            %li
              %a{:href => "#!"} Holidays
            %li
              %a{:href => "#!"} Love
            %li
              %a{:href => "#!"} Family
            %li
              %a{:href => "#!"} Elementary School
            %li
              %a{:href => "#!"} Jr High
            %li
              %a{:href => "#!"} High School                                          
            %li
              %a{:href => "#!"} Imagination
            %li
              %a{:href => "#!"} Image
            %li
              %a{:href => "#!"} Shape
            %li
              %a{:href => "#!"} Sound
            %li
              %a{:href => "#!"} Chants and Rhythm
            %li
              %a{:href => "#!"} Senses
            %li
              %a{:href => "#!"} Personification
            %li
              %a{:href => "#!"} Hyperbole
            %li
              %a{:href => "#!"} Juxtaposition
            %li
              %a{:href => "#!"} Onomatopoeia
            %li
              %a{:href => "#!"} Tanka
            %li
              %a{:href => "#!"} Memory
            %li
              %a{:href => "#!"} Sapphic Modernism
            %li
              %a{:href => "#!"} Muse
            %li
              %a{:href => "#!"} Superlatives
            %li
              %a{:href => "#!"} Metaphor/Simile
            %li
              %a{:href => "#!"} Sestinas
            %li
              %a{:href => "#!"} Ode
            %li
              %a{:href => "#!"} Ekphrasis
            %li
              %a{:href => "#!"} Riddles

          %p

          .form-row
            .input-group
              = label :poem, :title, 'Create Poem Tags'
              = text_field :poem, 'tag_list', :class => "entry_box", :id=> "poem_tags", :type => 'text', :placeholder => 'ex: Love, Seasons, Ode', :err => 'Poem Tags'
          .form-row
            .input-group
              = label :poem, :poem, 'Poem'
              = text_area :poem, 'poem', :class => "entry_box", :id => "poem_entry", :placeholder => 'input poem here', :class=> "form-control"
          .form-row
            .input-group
              = label :poem, :attachment, 'Attach Poem/Images'
              %p * Please combine multiple files into a single attachment prior to uploading.
              = file_field :poem, :attachment, :id => "poem_button", :err => 'Attach Poem/Images'
          -#.form-row
          -#  .input-group
          -#    %img#preview{:alt => "preview", :src => "http://golloscdn.com/common/no-image.jpg"} 
          .form-row
            .input-group
              = label :poem, :release, 'Release Form'
              %p
                * Download a blank student release form on the Secure Login page – section 3
                %a{:href => "http://www.californiapoets.org/secure-login", :style => "display: inline;"} here     
              = file_field :poem, :release, :id => "release_button", :err => 'Release Form'
          %br
          
          Having trouble? Click
          %a{:href => "http://www.californiapoets.org/contact-us", :target => "_blank", :style => "display: inline;"} here 
          to contact us for further assistance.
      -#= button_tag 'Add another student', :id => "addStudent", :type=>"button"
    %br
    %footer.footer
      = submit_tag 'Submit the poem', :id => "button", :class=>"button"
      

app/views/poems/show.html.haml
%html
  %head
    %title 
    = stylesheet_link_tag 'show'
    = csrf_meta_tags
.body
  .logo 
    = link_to image_tag("https://static.wixstatic.com/media/a0cfee_3825840911504adfac05ff6e22bf7b6c.jpg/v1/fill/w_198,h_134,al_c,q_80,usm_0.66_1.00_0.01/a0cfee_3825840911504adfac05ff6e22bf7b6c.webp", 
    ),'/'
  .container
    .header
      %h2 
        = @poem.title
      %h3 
        = @poem.student_name
        , Grade
        = @poem.grade
    %table#tag-table
      %thead
        %tr
          %th Tags
          %th Status
          %th Actions
      %tbody
        - @tag_objects.each do |tag|
          %tr
            %td= tag.name
            %td= tag.status
            - if tag.status == "Approved"
              %td= button_to( "Reject", tag_reject_path(tag.id))
            - if tag.status == "Rejected"
              %td= button_to( "Revive", tag_approve_path(tag.id))
            - if tag.status == "Pending"
              %td= button_to( "Approve", tag_approve_path(tag.id))
              %td= button_to( "Reject", tag_reject_path(tag.id))
    .container
      = form_tag tags_path(:id => @poem.id), :class => "newtag_form", :multipart => true do
        .form-row
          .input-group
            %h5 Add Tags
            = text_area :tag, 'new_tag_list', :class => "entry_box", :id => "tag_entry", :placeholder => 'e.g. Love, Seasons, Ode', :class=> "form-control"
          %footer.footer
            = submit_tag 'Submit Tag(s)', :id => "tag-button", :class=>"button"
    .content
      .main
        = simple_format(@poem.poem)
      .info
        %ol
          Poet Teacher: 
          = @poem.teacher_name
        %ol
          Teacher: 
          = link_to @poem.teacher_name, teacher_profile_poem_path(@poem.id)
        %ol
          School: 
          = @poem.school
        %ol
          County: 
          = @poem.county
        %ol
          = link_to "Download", @poem.attachment_url

app/views/poems/submitted.html.haml
= stylesheet_link_tag "submitted"

.container
  .info
    %h1 Poem was successfully submitted!
    %p * Please note: if you created new tags, they will also be reviewed along with the poem.
    %span
    %br
    %footer.footer
      = button_to 'Submit another poem', { action: "new" },  :method => :get, :id => "submit_another_button", :class=>"button"
      = button_to 'Return to Gallery', { action: "home" },  :method => :get, :id => "return_to_gallery", :class=>"button"

app/views/poems/teacher_profile.html.haml
%html
  %head
    %title 
    = stylesheet_link_tag 'teacherProfile'
    = csrf_meta_tags
.body
  .container
    .header
      %h2 
        = @poem.teacher_name
    .content
      .info
        .profile_pic
          %ol
            = image_tag (@page.at('.cbFormData img').attributes["src"]), width: "300px"
        .personal_info
          %ol
            Last Name:
            = @page.at(".cbFormTableEvenRow has(td[text()='Name Last'])").parent.at('span').text
          %ol
            First Name:
            = @page.at(".cbFormTableRow has(td[text()='Name First'])").parent.at('span').text
          %ol
            Title:
            = @page.at(".cbFormTableEvenRow has(td[text()='Title'])").parent.at('span').text
          %ol
            Email:
            = @page.at(".cbFormTableRow has(td[text()='Email'])").parent.at('span').text
          %ol
            City:
            = @page.at(".cbFormTableEvenRow has(td[text()='City'])").parent.at('span').text
          %ol
            County:
            = @page.at(".cbFormTableRow has(td[text()='County'])").parent.at('span').text
          %ol
            State:
            = @page.at(".cbFormTableEvenRow has(td[text()='State'])").parent.at('span').text
          %ol
            Zip:
            = @page.at(".cbFormTableRow has(td[text()='Zip'])").parent.at('span').text
            
        .other_info
          %ol
            %h3
              Bio
            %p
              = @page.at(".cbFormTableEvenRow has(td[text()='Bio'])").parent.at('span').text
          %ol
            %h3
              Sample Poem
            = @page.at(".cbFormTableEvenRow has(td[text()='Sample poem'])").parent.at('span').text
          %ol
            = button_to "Go Back", '#', :onclick => 'history.back(); return false;'