config/routes.rb
Rails.application.routes.draw do
  
  
  resources :tags, except: [:index] do
    authenticated :user do
      post 'approve'
      post 'reject'
    end
  end
  
  get '/home/', to: 'poems#home'

  get '/admin/', to: 'admin#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
    
  authenticated :user do
    get '/poems/', to:'poems#index', as: :view_poems
    
    get '/tags', to: 'tags#index', as: :view_tags
  
    get 'poems/submitted/', to: 'poems#submitted'

    resources :poems, except: [:index] do
      member do
        post 'approve'
        post 'reject'
        get 'teacher_profile'
      end
    end

  end
  
  unauthenticated :user do
   get '/poems/', to: 'poems#home'
  end

  if Rails.env.production?
     get '404', :to => 'application#page_not_found'
  end

  root to: 'poems#home'

  

  

end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :poems
    after_initialize :init

    def init
      self.status  ||= "Pending"           #will set the default value only if it's nil
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    
    def tag_params
        params.require(:tag).permit(:new_tag_list)
    end
    
    def index
        @tags = Tag.all.order('created_at DESC')
    end
    
    # def tag_index
    #     @
    
    # def show
    #     id = params[:id]
    #     @poem = Poem.find(id)
    #     @url_test = request.base_url
    #     @url_test = "http://" + @url_test[8, @url_test.length]
    # end
    
    # def new
    
    # end
    
    def approve 
        tag = Tag.find(params[:tag_id])
        #revive function
        if tag[:status].to_s == "Rejected"
            tag.update_attributes(:status => "Pending")
            #if not from admin tag page, but from poems show page
            # if current_page?(controller: 'poems', action: 'show')
            #     redirect_back(fallback_location: fallback_location)
            # else
            #     redirect_to view_tags_url
            # end
            redirect_to view_tags_url
        else
            tag.update_attributes(:status => "Approved")
            flash[:notice] = "You successfully approved this tag."
            #if not from admin tag page, but from poems show page
            # if current_page?(controller: 'poems', action: 'show')
            #     redirect_back(fallback_location: fallback_location)
            # else
            #     redirect_to view_tags_url
            # end
            redirect_to view_tags_url
        end
    end
    
    def reject
        tag = Tag.find(params[:tag_id])
        tag.update_attributes(:status => "Rejected")
        flash[:notice] = "You successfully rejected this tag."
        redirect_to view_tags_url
    end
    
    def create
        if params[:id]
            tag_array = params[:tag][:new_tag_list].split(/[\s,]+/)
            @poem = Poem.find(params[:id])
        else
            tags = tag_params
            tag_array = tags[:new_tag_list].split(/[\s,]+/)
        end
        duplicates = []
        checked_tags = tag_array
        
        #sanitation check (e.g. no duplicates)
        tag_array.each do |tag|
            #tag is a string, use it to check if the tag already exists in db.
            #if it already exists in database, give pop up box alerting user that duplicate tag will not be created.
            if Tag.find_by(name: tag).present?
                duplicates.push(tag)
                checked_tags = tag_array - [tag]
            end
        end
        
        if duplicates.length > 0
            flash[:warning] = "\"#{duplicates.to_sentence}\"" + " already exist(s) in the database. Non-duplicates successfully added."
            # render :template => "index"
        end
        
        #for all valid tags in checked_tags array, add them into the database.
        checked_tags.each do |tag|
            new_tag = Tag.new(:name => tag, :status => "Pending")
            if params[:id]
                @poem.tag_list.add(tag, parse: true)
                @poem.save!
            elsif not new_tag.save
                puts new_tag.status
                flash[:warning] = "Please fix formatting."
                render view_tags_path
            end
        end
        
        if params[:id]
            session[:return_to] ||= request.referer
            redirect_to session.delete(:return_to)
        else
            redirect_to view_tags_path
        end
        #ASSUMPTIONS: by checking for duplication at time of creation, the database will never have any duplicate tags.
    end
    
    # def home
    #     @poems = Poem.where("status = 'Approved'").order(:created_at).reverse_order.paginate(page: params[:page], per_page: 9)
    # end
    
    
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.haml
= stylesheet_link_tag "admindash"
= javascript_include_tag 'admindash'

// .rightbutton= link_to 'Log Out', destroy_user_session_path, :method=>'delete', :class=>"btn white logout"

// .rightbutton= link_to 'Gallery', '/home?', :method=>'get', :class=>"btn white gallery"

%h1 List of All Submitted Tags in Database

.container
	.switch-button
		%div#options
			%div 
				=link_to "Poems", view_poems_path,  :class=>"btn white poem-tag"
			%div 
				=link_to "Tags", view_tags_path, :class=>"btn white poem-tag"
	.tabs-container
		%ul.tabs
			%li
				=link_to "Create Tags", "javascript:openTab(event, 'tab-0')", :id => "current", :class => "tab-link"
			%li
				=link_to "Pending Approval", "javascript:openTab(event, 'tab-1')", :class => "tab-link"
			%li 
				=link_to "All Tags", "javascript:openTab(event, 'tab-2')", :class => "tab-link"
			%li 
				=link_to "Approved Tags", "javascript:openTab(event, 'tab-3')", :class => "tab-link"
			%li 
				=link_to "Rejected Tags", "javascript:openTab(event, 'tab-4')", :class => "tab-link"
			
		#tab-0.tab-content
			= form_tag tags_path, :class => "newtag_form", :multipart => true do
				.form-row
					.input-group
						%h5 Create Tags
						%p Enter a tag or a list of tags in the input box below. Capitalize the first letter, and separate each tag by a comma and a space.
						// = label :poem, :poem, 'Poem'
						= text_area :tag, 'new_tag_list', :class => "entry_box", :id => "tag_entry", :placeholder => 'e.g. Love, Seasons, Ode', :class=> "form-control"
				%footer.footer
					= submit_tag 'Submit Tag(s)', :id => "tag-button", :class=>"button"
				%footer.footer
					= Poem.first.tag_list.length
		#tab-1.tab-content
			%table#poems
				%thead
					%tr
						%th Tag
						%th Actions
				%tbody
					- @tags.each do |tag| 
						- if tag.status == "Pending"
							%tr
								%td= tag.name
								%td= button_to( "Approve", tag_approve_path(tag.id))
								%td= button_to( "Reject", tag_reject_path(tag.id))
		#tab-2.tab-content
			%table#poems
				%thead
					%tr
						%th Tag
						%th Status
				%tbody
					- @tags.each do |tag| 
						%tr
							%td= tag.name
							%td= tag.status
		#tab-3.tab-content
			%table#poems
				%thead
					%tr
						%th Tag
						%th Actions
				%tbody
					- @tags.each do |tag|
						- if tag.status == "Approved"
							%tr
								%td= tag.name
								%td= button_to( "Reject", tag_reject_path(tag.id))
		#tab-4.tab-content
			%table#poems
				%thead
					%tr
						%th Tag
						%th Actions
				%tbody
					- @tags.each do |tag|
						- if tag.status == "Rejected"
							%tr
								%td= tag.name
								%td= button_to( "Revive", tag_approve_path(tag.id))
					
%script
	document.getElementById("current").click();