config/routes.rb
Rails.application.routes.draw do
  
  
  resources :tags, except: [:index] do
    authenticated :user do
      post 'approve'
      post 'reject'
    end
  end
  
  get '/home/', to: 'poems#home'

  get '/admin/', to: 'admin#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
    
  authenticated :user do
    get '/poems/', to:'poems#index', as: :view_poems
    
    get '/tags', to: 'tags#index', as: :view_tags
  
    get 'poems/submitted/', to: 'poems#submitted'

    resources :poems, except: [:index] do
      member do
        post 'approve'
        post 'reject'
        get 'teacher_profile'
      end
    end

  end
  
  unauthenticated :user do
   get '/poems/', to: 'poems#home'
  end

  if Rails.env.production?
     get '404', :to => 'application#page_not_found'
  end

  root to: 'poems#home'

  

  

end

app/views/layouts/application.html.haml
%html
  %head
    %title California Poets in the Schools
    = javascript_include_tag 'application'
    = javascript_include_tag 'https://code.jquery.com/jquery-2.2.4.js'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js'
    = stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/css/materialize.min.css'
    = stylesheet_link_tag 'adminlogin'
    = csrf_meta_tags

  %body
    %nav
      .nav-wrapper
        .brand-logo.right
          %a{:href => "http://www.californiapoets.org/"}
            California Poets in the Schools
            %img.right{:src => "https://static.wixstatic.com/media/a0cfee_3825840911504adfac05ff6e22bf7b6c.jpg/v1/fill/w_198,h_134,al_c,q_80,usm_0.66_1.00_0.01/a0cfee_3825840911504adfac05ff6e22bf7b6c.webp", :style => "width: 93px; height: auto;"}
        %ul#nav-mobile.left
          %li= link_to 'Home', root_path, :method=>'get'
          -if not current_user.nil?
            %li= link_to 'Admin', view_poems_path
          -if not current_user.nil?
            %li= link_to 'Submit a Poem', new_poem_path
          -if current_user.nil?
            %li= link_to 'Log In / Sign up', admin_path
          -else
            %li= link_to 'Log Out', destroy_user_session_path, :method=>'delete'
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
      = yield
  %script